# Generated by Django 4.2.3 on 2023-11-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ArticulosBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog', models.CharField(max_length=250)),
                ('articule_url', models.SlugField()),
                ('body', models.TextField()),
                ('data_create', models.DateField(auto_now_add=True)),
                ('article_modificado', models.DateField(auto_now=True)),
                ('imagen_article', models.FileField(upload_to='blog/articles')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogHome.reporter', verbose_name='Reportero')),
            ],
            options={
                'verbose_name': 'ArticulosBlog',
                'verbose_name_plural': 'ArticulosBlogs',
            },
        ),
    ]
