# Generated by Django 4.2.3 on 2023-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulosBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog', models.CharField(max_length=250)),
                ('articule_url', models.SlugField()),
                ('body', models.TextField()),
                ('data_create', models.DateField(auto_now_add=True)),
                ('article_modificado', models.DateField(auto_now=True)),
                ('imagen_article', models.FileField(upload_to='blog/articles')),
            ],
            options={
                'verbose_name': 'ArticulosBlog',
                'verbose_name_plural': 'ArticulosBlogs',
            },
        ),
    ]
